name: "TMS Docker Build"
description: "Build docker image and push to azurecr"
inputs:
  tag:
    description: 'docker tag'
    required: true
  azure-container-registry:
    escription: 'azure cr registry'
    required: true
  azure-container-registry-username:
    description: 'azure cr username'
    required: true
  azure-container-registry-password:
    description: 'azure cr password'
    required: true
  port-container-image-webhook:
    description: 'webhook to publish container image to Port'
  github-token:
    description: 'github token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: "Docker build"
      run: docker build --build-arg GH_TOKEN=${{ inputs.github-token }} -t ${{ github.event.repository.name }}:${{ inputs.tag }} .
      shell: bash
    - name: "Docker push"
      run: |
        docker login -u ${{ inputs.azure-container-registry-username }} -p ${{ inputs.azure-container-registry-password }} ${{ inputs.azure-container-registry }}
        docker tag ${{ github.event.repository.name }}:${{ inputs.tag }} temoprod.azurecr.io/${{ github.event.repository.name }}:latest
        docker tag ${{ github.event.repository.name }}:${{ inputs.tag }} temoprod.azurecr.io/${{ github.event.repository.name }}:${{ inputs.tag }}
        docker push temoprod.azurecr.io/${{ github.event.repository.name }}:latest
        docker push temoprod.azurecr.io/${{ github.event.repository.name }}:${{ inputs.tag }}
      shell: bash
    - name: "Add container to Port"
      if: ${{ inputs.port-container-image-webhook != '' }}
      shell: bash
      run: |
        curl -X POST ${{ inputs.port-container-image-webhook }} -H "Content-Type: application/json" -d '{"image_name":"${{ github.event.repository.name }}","tag":"${{ inputs.tag }}"}'
