name: "TMS Docker Build"
description: "Build docker image and push to azurecr"
inputs:
  tag:
    description: 'dockee tag'
    required: true
  azurecr-reqistry:
    escription: 'azure cr registry'
    required: true
  azurecr-username:
    description: 'azure cr username'
    required: true
  azurecr-password:
    description: 'azure cr password'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: "Docker build"
      run: docker build -t ${{ github.event.repository.name }}:${{ inputs.tag }} .
      shell: bash
    - name: "Docker push"
      run: |
        docker login -u ${{ inputs.azurecr-username }} -p ${{ inputs.azurecr-password }} ${{ inputs.azurecr-reqistry }}
        docker tag ${{ github.event.repository.name }}:${{ inputs.tag }} temoprod.azurecr.io/${{ github.event.repository.name }}:latest
        docker tag ${{ github.event.repository.name }}:${{ inputs.tag }} temoprod.azurecr.io/${{ github.event.repository.name }}:${{ inputs.tag }}
        docker push temoprod.azurecr.io/${{ github.event.repository.name }}:latest
        docker push temoprod.azurecr.io/${{ github.event.repository.name }}:${{ inputs.tag }}
      shell: bash
